### ISSUE TITLE
office contacts Opps 

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#35]
![1](https://cloud.githubusercontent.com/assets/15248543/19071256/c5eec74a-89f4-11e6-8dff-39fe291366cb.png)
Getting this popping up

**Comment by kevinheath** [comment]
This happens when I try and save contact. Not letting me save

**Comment by baansconsulting** [comment]
this is happening as we have added a check to not allow duplicate email id for contacts

**Comment by kevinheath** [comment]
Should this be caught when the email is placed the 2nd time?

**Comment by kevinheath** [comment]
Also I changed the email in work and still not allowing me to save

**Comment by kevinheath** [comment]
Also I removed the email in work and still not letting me save

**Comment by baansconsulting** [comment]
done.

**Comment by kevinheath** [comment]
Still not working - should catch duplicate in contact and duplicate for all contacts in a client
